gcloud run deploy SERVICE $CLOUD_RUN_INSTANCE_NAME --image  $CLOUD_RUN_LOCATION \
 --update-env-vars \
 SQL_DATABASE_USER="$SQL_DATABASE_USER", \
 SQL_DATABASE_PASSWORD="$SQL_DATABASE_PASSWORD", \
 SQL_DATABASE_INSTANCE="$SQL_DATABASE_INSTANCE", \
 KAFKA_DATABASE_USER="$KAFKA_DATABASE_USER", \
 KAFKA_DATABASE_PASSWORD="$KAFKA_DATABASE_PASSWORD", \
 KAFKA_DATABASE_INSTANCE="$KAFKA_DATABASE_INSTANCE", \
 ELASTIC_AUTH_BASIC_TOKEN="$ELASTIC_AUTH_BASIC_TOKEN", \
 ELASTIC_INSTANCE_URL="$ELASTIC_INSTANCE_URL", \
 REDIS_IP_ADDRESS="$REDIS_IP_ADDRESS"