docker build -t $DOCKER_IMAGE_REPOSITORY:$DOCKER_IMAGE_VERSION . \
#--build-arg VERSION=$VERSION \
#--build-arg SQL_DATABASE_USER=$SQL_DATABASE_USER \
#--build-arg SQL_DATABASE_PASSWORD=$SQL_DATABASE_PASSWORD \
#--build-arg SQL_DATABASE_INSTANCE=$SQL_DATABASE_INSTANCE \
#--build-arg KAFKA_DATABASE_USER=$KAFKA_DATABASE_USER \
#--build-arg KAFKA_DATABASE_PASSWORD=$KAFKA_DATABASE_PASSWORD \
#--build-arg KAFKA_DATABASE_INSTANCE=$KAFKA_DATABASE_INSTANCE \
#--build-arg ELASTIC_AUTH_BASIC_TOKEN=$ELASTIC_AUTH_BASIC_TOKEN \
#--build-arg ELASTIC_INSTANCE_URL=$ELASTIC_INSTANCE_URL