version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/code
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: Check dependencies
          command: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Run Unit tests
          command: ./gradlew test
      - run:
          name: Assemble build
          command: ./gradlew assemble
      - run:
          name: Export version const
          command: export VERSION=`cat version.txt`
      - run:
          name: Echo version const
          command: echo $VERSION
      - run:
          name: Build docker image
          command: docker build -t dvpermyakov/public-poll:$VERSION . --build-arg VERSION=$VERSION
      - run:
          name: Docker login
          command: echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Publish docker image
          command: docker push dvpermyakov/public-poll:$VERSION