version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/code
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: Check dependencies
          command: ./gradlew dependencies
      - run:
          name: Increase version
          command: |
            git config user.name $GIT_USERNAME
            git config user.email $GIT_USEREMAIL
            git clone https://github.com/dvpermyakov/increment-version-bash.git
            cd increment-version-bash/
            chmod u+x ./increment.sh
            ./increment.sh
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Run Unit tests
          command: ./gradlew test
      - run:
          name: Assemble build
          command: ./gradlew assemble
      - run:
          name: Publish docker image
          command: |
            export VERSION=`cat version.txt`
            echo $VERSION
            docker build -t dvpermyakov/public-poll:$VERSION . --build-arg VERSION=$VERSION
            echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
            docker push dvpermyakov/public-poll:$VERSION